name: tag-v2

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Tag ${{ github.event.inputs.tag }} as v2
        run: |
          git tag v2 -f
          git push origin --tags -f
